version: '3.7'
services:
  postgresql:
    image: postgres:12-alpine
    ports:
      - '3306:3306'
    volumes:
      - ./data:/var/lib/postgresql
    environment:
      POSTGRES_USER = superUser
      POSTGRES_PASSWORD=ff243fdsf$%fdsf
      POSTGRES_DB = app